### ISSUE TITLE
Broken in Mac OS X 10.12 (Sierra)

### ISSUE THREAD

**Issue by ybizeul** [cguy/todoist-cli#3]
```
yann$ ./todoist 
Killed: 9
```

**Comment by cguy** [comment]
I just rebuilt the app without code modification, please find the 0.0.2 release with binary: todoist-0.0.2-darwin-amd64

**Comment by ybizeul** [comment]
Thank you.

Are you sure you're building against an updated uuid?

`CleanHyphen` is nowhere to be found in twinj/uuid :

From format.go :
```
const (
	FormatHex        Format = "%x%x%x%x%x"
	FormatHexCurly   Format = "{%x%x%x%x%x}"
	FormatHexBracket Format = "(%x%x%x%x%x)"

	// This is the canonical format.
	FormatCanonical Format = "%x-%x-%x-%x-%x"

	FormatCanonicalCurly   Format = "{%x-%x-%x-%x-%x}"
	FormatCanonicalBracket Format = "(%x-%x-%x-%x-%x)"
	FormatUrn              Format = "urn:uuid:" + FormatCanonical
)
```

**Comment by cguy** [comment]
Sure I am NOT :) but I don't think it really matters for the current build.

I will accept your pull request when I have the time (and test if my project still works)

**Comment by ybizeul** [comment]
Ok I see, yes for the purpose of that ticket, a simple rebuild does the job, I finally managed to build my own, I'm clear! Merci!
